FROM maven:3.6.3-amazoncorretto-11

WORKDIR /

COPY . ./

RUN mvn clean install --fail-never -B -DfailIfNoTests=false

RUN mkdir -p /app

ADD ./tmp/target/spring-boot-mysql-0.0.1-SNAPSHOT.jar /app








